services:
  - type: web
    name: discord-bot-vinhedo
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npx tsx server/index.prod.ts
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
    autoDeploy: true
    regions:
      - ohio